version: "3.3"
# Указываем раздел со связанными сервисами

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      # Заменить на свой nginx конфиг
      - ./nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./logs:/var/log/nginx/
    networks:
      back_front_nginx: {}
    restart: always

networks:
  back_front_nginx:
    external: true